---
- name: Installing cQube NVSK
  hosts: localhost
  gather_facts: true
  remote_user: root
  vars_files:
    - ../config.yml

  roles:

          - workflow_createdb 
          - nifi_workflow_install
          - { role: nifi_params, tags: install }
            
          - role: validate
            tags: install

          - role: configurable
            tags: install

          - role: transaction_and_aggregation
            tags: install

