- name: Create directory with mode setting 
  file:
    path: /tmp/postgres
    owner: postgres
    state: directory
    mode: "1755"
  tags: [ install, update ]

- name: copy required files to /tmp/postgres
  copy:
    src: "../../development/datasource/static/postgres/{{ item }}"
    dest: /tmp/postgres
    owner: postgres
    mode: "0644"
  loop:
    - static_queries.sql
    - static_tables.sql
    - truncate_tables.sql
  tags: [ install, update ]

- name: copy required files to /tmp/postgres
  copy:
    src: "../../development/datasource/diksha/postgres/{{ item }}"
    dest: /tmp/postgres
    owner: postgres
    mode: "0644"
  loop:
    - diksha_queries.sql
    - diksha.sql
  tags: [ install, update ]
  when: diksha

- name: Truncating previous tables
  shell: psql "host=localhost dbname={{ db_name }} user={{ db_user }} password={{ db_password }}" -a -q -f "/tmp/postgres/truncate_tables.sql"
  when: datasource_status == "unmatched"
  tags: [ install, update ]

- name: Clearing s3 output bucket data
  shell: AWS_ACCESS_KEY_ID={{ s3_access_key }} AWS_SECRET_ACCESS_KEY={{ s3_secret_key}} aws s3 rm s3://{{ s3_output_bucket }}  --recursive
  when: storage_type == "s3" and datasource_status == "unmatched"
  tags: [ install, update ]

- name: Clearing local output folder data
  shell: rm -rf "{{ output_directory }}"*
  args:
    warn: false
  when: storage_type == "local" and datasource_status == "unmatched"
  tags: [ install, update ]
  
- name: Create database user
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ read_only_db_user }}"
    password: "{{ read_only_db_password }}"
    encrypted: yes
    state: present
  tags: install

- name: Grant the SELECT privilege to the read_only_db_user
  become: true
  become_user: postgres
  postgresql_privs:
    db: "{{ db_name }}"
    privs: SELECT
    objs: ALL_IN_SCHEMA
    role: "{{ read_only_db_user }}"
  tags: install

- name: Stopping postgresql 
  service: 
    name: postgresql
    state: stopped
  tags: [ install, update ]

- name: Starting postgresql
  service: 
    name: postgresql
    state: started
  tags: [ install, update ]
