---
- name: Creating the server_side Directory for the installation
  file: 
    path: "{{ base_dir }}/cqube/dashboard/server_side"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
    state: directory
  tags: [ install, update ]

- name: copying server-side script
  copy:
    src: "../../development/ui/back-end/"
    dest: "{{base_dir}}/cqube/dashboard/server_side"
  tags: [ install, update ] 

- name: NodeJS dependencies install
  npm:
    path: "{{base_dir}}/cqube/dashboard/server_side"
  tags: [ install, update ]
